MODEL:
  TYPE: generalized_rcnn
  SUBTYPE: 3
  USE_OVLP_FILTER: False
  USE_FREQ_BIAS: True
  NO_FC7_RELU: True
  CONV_BODY: VGG16.VGG16_conv_body
  FASTER_RCNN: True
  USE_SEPARATE_SO_SCORES: True
  NORM_SCALE: 3.0
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 7560  # 7560 roidbs
  STEPS: [0, 5040, 6720]
VGG16:
  VRD_PRETRAINED_WEIGHTS: 'models/vrd/model_COCO_pretrained.pth'
  VRD_PRD_PRETRAINED_WEIGHTS: 'models/vrd/model_COCO_pretrained.pth'
FAST_RCNN:
  ROI_BOX_HEAD: VGG16.VGG16_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
RPN:
  SIZES: (32, 64, 128, 256, 512)
TRAIN:
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
TEST:
  FORCE_JSON_DATASET_EVAL: True
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  DETECTIONS_PER_IM: 100
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
